<?php

namespace Database\Seeders\rpg;

use App\Enums\Rpg\EnemyData;
use App\Models\Game\Rpg\Enemy;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class EnemyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        Enemy::truncate();

        $enemies = [
            [
                'id' => EnemyData::Srara,
                'name' => EnemyData::Srara->label(),
                'value_hp' => 80,
                'value_ap' => 0,
                'value_str' => 15,
                'value_def' => 10,
                'value_int' => 0,
                'value_spd' => 1,
                'value_luc' => 0,
                'exp' => 15,
                'drop_money' => 10,
                'portrait_image_path' => EnemyData::Srara->image_path(),
                'description' => EnemyData::Srara->description(),
                'is_boss' => false,
                'has_pattern' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::Gao,
                'name' => EnemyData::Gao->label(),
                'value_hp' => 100,
                'value_ap' => 0,
                'value_str' => 25,
                'value_def' => 10,
                'value_int' => 0,
                'value_spd' => 30,
                'value_luc' => 0,
                'exp' => 25,
                'drop_money' => 15,
                'portrait_image_path' => EnemyData::Gao->image_path(),
                'description' => EnemyData::Gao->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::BigSrara,
                'name' => EnemyData::BigSrara->label(),
                'value_hp' => 150,
                'value_ap' => 30,
                'value_str' => 20,
                'value_def' => 10,
                'value_int' => 1,
                'value_spd' => 15,
                'value_luc' => 0,
                'exp' => 30,
                'drop_money' => 20,
                'portrait_image_path' => EnemyData::BigSrara->image_path(),
                'description' => EnemyData::BigSrara->description(),
                'is_boss' => true,
                'has_pattern' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::Lizard,
                'name' => EnemyData::Lizard->label(),
                'value_hp' => 130,
                'value_ap' => 20,
                'value_str' => 25,
                'value_def' => 55,
                'value_int' => 0,
                'value_spd' => 35,
                'value_luc' => 0,
                'exp' => 50,
                'drop_money' => 20,
                'portrait_image_path' => EnemyData::Lizard->image_path(),
                'description' => EnemyData::Lizard->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::Scorpio,
                'name' => EnemyData::Scorpio->label(),
                'value_hp' => 80,
                'value_ap' => 0,
                'value_str' => 30,
                'value_def' => 60,
                'value_int' => 0,
                'value_spd' => 20,
                'value_luc' => 800,
                'exp' => 60,
                'drop_money' => 20,
                'portrait_image_path' => EnemyData::Scorpio->image_path(),
                'description' => EnemyData::Scorpio->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::RockLizard,
                'name' => EnemyData::RockLizard->label(),
                'value_hp' => 400,
                'value_ap' => 30,
                'value_str' => 50,
                'value_def' => 80,
                'value_int' => 0,
                'value_spd' => 40,
                'value_luc' => 0,
                'exp' => 75,
                'drop_money' => 50,
                'portrait_image_path' => EnemyData::RockLizard->image_path(),
                'description' => EnemyData::RockLizard->description(),
                'is_boss' => true,
                'has_pattern' => false,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => EnemyData::Norawani,
                'name' => EnemyData::Norawani->label(),
                'value_hp' => 450,
                'value_ap' => 40,
                'value_str' => 40,
                'value_def' => 60,
                'value_int' => 60,
                'value_spd' => 40,
                'value_luc' => 0,
                'exp' => 90,
                'drop_money' => 25,
                'portrait_image_path' => EnemyData::Norawani->image_path(),
                'description' => EnemyData::Norawani->description(),
                'has_pattern' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::Bou,
                'name' => EnemyData::Bou->label(),
                'value_hp' => 60,
                'value_ap' => 30,
                'value_str' => 10,
                'value_def' => 0,
                'value_int' => 50,
                'value_spd' => 15,
                'value_luc' => 0,
                'exp' => 20,
                'drop_money' => 10,
                'portrait_image_path' => EnemyData::Bou->image_path(),
                'description' => EnemyData::Bou->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::IwaMet,
                'name' => EnemyData::IwaMet->label(),
                'value_hp' => 300,
                'value_ap' => 0,
                'value_str' => 55,
                'value_def' => 120,
                'value_int' => 10,
                'value_spd' => 25,
                'value_luc' => 0,
                'exp' => 60,
                'drop_money' => 20,
                'portrait_image_path' => EnemyData::IwaMet->image_path(),
                'description' => EnemyData::IwaMet->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::MagmaDile,
                'name' => EnemyData::MagmaDile->label(),
                'value_hp' => 700,
                'value_ap' => 40,
                'value_str' => 55,
                'value_def' => 70,
                'value_int' => 40,
                'value_spd' => 40,
                'value_luc' => 0,
                'exp' => 100,
                'drop_money' => 60,
                'portrait_image_path' => EnemyData::MagmaDile->image_path(),
                'description' => EnemyData::MagmaDile->description(),
                'is_boss' => true,
                'has_pattern' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => EnemyData::MageSrara,
                'name' => EnemyData::MageSrara->label(),
                'value_hp' => 100,
                'value_ap' => 20,
                'value_str' => 5,
                'value_def' => 5,
                'value_int' => 50,
                'value_spd' => 25,
                'value_luc' => 0,
                'exp' => 30,
                'drop_money' => 20,
                'portrait_image_path' => EnemyData::MageSrara->image_path(),
                'description' => EnemyData::MageSrara->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::Clion,
                'name' => EnemyData::Clion->label(),
                'value_hp' => 150,
                'value_ap' => 40,
                'value_str' => 5,
                'value_def' => 0,
                'value_int' => 55,
                'value_spd' => 10,
                'value_luc' => 0,
                'exp' => 40,
                'drop_money' => 22,
                'portrait_image_path' => EnemyData::Clion->image_path(),
                'description' => EnemyData::Clion->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::Ikkaku,
                'name' => EnemyData::Ikkaku->label(),
                'value_hp' => 300,
                'value_ap' => 30,
                'value_str' => 50,
                'value_def' => 10,
                'value_int' => 130,
                'value_spd' => 30,
                'value_luc' => 0,
                'exp' => 55,
                'drop_money' => 25,
                'portrait_image_path' => EnemyData::Ikkaku->image_path(),
                'description' => EnemyData::Ikkaku->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::SpikeWhale,
                'name' => EnemyData::SpikeWhale->label(),
                'value_hp' => 650,
                'value_ap' => 200,
                'value_str' => 45,
                'value_def' => 30,
                'value_int' => 80,
                'value_spd' => 35,
                'value_luc' => 0,
                'exp' => 100,
                'drop_money' => 50,
                'portrait_image_path' => EnemyData::SpikeWhale->image_path(),
                'description' => EnemyData::SpikeWhale->description(),
                'is_boss' => true,
                'has_pattern' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::Nepenthos,
                'name' => EnemyData::Nepenthos->label(),
                'value_hp' => 700,
                'value_ap' => 50,
                'value_str' => 48,
                'value_def' => 20,
                'value_int' => 85,
                'value_spd' => 55,
                'value_luc' => 0,
                'exp' => 160,
                'drop_money' => 120,
                'portrait_image_path' => EnemyData::Nepenthos->image_path(),
                'description' => EnemyData::Nepenthos->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::Dionaea,
                'name' => EnemyData::Dionaea->label(),
                'value_hp' => 700,
                'value_ap' => 50,
                'value_str' => 50,
                'value_def' => 20,
                'value_int' => 100,
                'value_spd' => 50,
                'value_luc' => 0,
                'exp' => 160,
                'drop_money' => 120,
                'portrait_image_path' => EnemyData::Dionaea->image_path(),
                'description' => EnemyData::Dionaea->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::HazardBerry,
                'name' => EnemyData::HazardBerry->label(),
                'value_hp' => 400,
                'value_ap' => 100,
                'value_str' => 50,
                'value_def' => 0,
                'value_int' => 20,
                'value_spd' => 10,
                'value_luc' => 0,
                'exp' => 100,
                'drop_money' => 70,
                'portrait_image_path' => EnemyData::HazardBerry->image_path(),
                'description' => EnemyData::HazardBerry->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::WandEater,
                'name' => EnemyData::WandEater->label(),
                'value_hp' => 1500,
                'value_ap' => 100,
                'value_str' => 52,
                'value_def' => 50,
                'value_int' => 70,
                'value_spd' => 65,
                'value_luc' => 0,
                'exp' => 300,
                'drop_money' => 300,
                'portrait_image_path' => EnemyData::WandEater->image_path(),
                'description' => EnemyData::WandEater->description(),
                'is_boss' => true,
                'has_pattern' => true,
                'image_aspect_ratio' => '2/1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::Eripen,
                'name' => EnemyData::Eripen->label(),
                'value_hp' => 550,
                'value_ap' => 30,
                'value_str' => 55,
                'value_def' => 150,
                'value_int' => 15,
                'value_spd' => 120,
                'value_luc' => 0,
                'exp' => 200,
                'drop_money' => 200,
                'has_pattern' => true,
                'portrait_image_path' => EnemyData::Eripen->image_path(),
                'description' => EnemyData::Eripen->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::IceFairy,
                'name' => EnemyData::IceFairy->label(),
                'value_hp' => 1100,
                'value_ap' => 10, // HailShot 2発分
                'value_str' => 105,
                'value_def' => 200,
                'value_int' => 30,
                'value_spd' => 70,
                'value_luc' => 0,
                'exp' => 500,
                'drop_money' => 250,
                'has_pattern' => true,
                'portrait_image_path' => EnemyData::IceFairy->image_path(),
                'description' => EnemyData::IceFairy->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::ScissorFlipper,
                'name' => EnemyData::ScissorFlipper->label(),
                'value_hp' => 1200,
                'value_ap' => 100,
                'value_str' => 60,
                'value_def' => 200,
                'value_int' => 20,
                'value_spd' => 130,
                'value_luc' => 0,
                'exp' => 500,
                'drop_money' => 500,
                'portrait_image_path' => EnemyData::ScissorFlipper->image_path(),
                'description' => EnemyData::ScissorFlipper->description(),
                'is_boss' => true,
                'has_pattern' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::HoshiHotaru,
                'name' => EnemyData::HoshiHotaru->label(),
                'value_hp' => 750,
                'value_ap' => 200,
                'value_str' => 20,
                'value_def' => 30,
                'value_int' => 240,
                'value_spd' => 80,
                'value_luc' => 0,
                'exp' => 230,
                'drop_money' => 180,
                'portrait_image_path' => EnemyData::HoshiHotaru->image_path(),
                'description' => EnemyData::HoshiHotaru->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::Gyao,
                'name' => EnemyData::Gyao->label(),
                'value_hp' => 450,
                'value_ap' => 100,
                'value_str' => 50,
                'value_def' => 10,
                'value_int' => 240,
                'value_spd' => 70,
                'value_luc' => 0,
                'exp' => 220,
                'drop_money' => 170,
                'portrait_image_path' => EnemyData::Gyao->image_path(),
                'description' => EnemyData::Gyao->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::ShadowWeed,
                'name' => EnemyData::ShadowWeed->label(),
                'value_hp' => 800,
                'value_ap' => 10,
                'value_str' => 70,
                'value_def' => 10,
                'value_int' => 350,
                'value_spd' => 55,
                'value_luc' => 0,
                'exp' => 240,
                'drop_money' => 150,
                'portrait_image_path' => EnemyData::ShadowWeed->image_path(),
                'description' => EnemyData::ShadowWeed->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::Twilight,
                'name' => EnemyData::Twilight->label(),
                'value_hp' => 2200,
                'value_ap' => 200,
                'value_str' => 80,
                'value_def' => 20,
                'value_int' => 250,
                'value_spd' => 75,
                'value_luc' => 0,
                'exp' => 700,
                'drop_money' => 700,
                'portrait_image_path' => EnemyData::Twilight->image_path(),
                'description' => EnemyData::Twilight->description(),
                'is_boss' => true,
                'has_pattern' => true,
                'image_aspect_ratio' => '2/1',
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // DecayedFarmland
            [
                'id' => EnemyData::CurseScareCrow,
                'name' => EnemyData::CurseScareCrow->label(),
                'value_hp' => 10000,
                'value_ap' => 50,
                'value_str' => 0,
                'value_def' => 0,
                'value_int' => 0,
                'value_spd' => 10,
                'value_luc' => 0,
                'exp' => 200,
                'drop_money' => 200,
                'portrait_image_path' => EnemyData::CurseScareCrow->image_path(),
                'description' => EnemyData::CurseScareCrow->description(),
                'has_pattern' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::ZombieClion,
                'name' => EnemyData::ZombieClion->label(),
                'value_hp' => 600,
                'value_ap' => 100,
                'value_str' => 100,
                'value_def' => 0,
                'value_int' => 0,
                'value_spd' => 90,
                'value_luc' => 0,
                'exp' => 600,
                'drop_money' => 450,
                'portrait_image_path' => EnemyData::ZombieClion->image_path(),
                'description' => EnemyData::ZombieClion->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::Narehate,
                'name' => EnemyData::Narehate->label(),
                'value_hp' => 6500,
                'value_ap' => 87,
                'value_str' => 121,
                'value_def' => 189,
                'value_int' => 87,
                'value_spd' => 57,
                'value_luc' => 87,
                'exp' => 5000,
                'drop_money' => 3000,
                'portrait_image_path' => EnemyData::Narehate->image_path(),
                'description' => EnemyData::Narehate->description(),
                'is_boss' => true,
                'has_pattern' => true,
                'image_aspect_ratio' => '2/1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // CastleTown
            [
                'id' => EnemyData::BazaarLizard,
                'name' => EnemyData::BazaarLizard->label(),
                'value_hp' => 660,
                'value_ap' => 40,
                'value_str' => 70,
                'value_def' => 190,
                'value_int' => 10,
                'value_spd' => 80,
                'value_luc' => 0,
                'exp' => 510,
                'drop_money' => 300,
                'portrait_image_path' => EnemyData::BazaarLizard->image_path(),
                'description' => EnemyData::BazaarLizard->description(),
                'has_pattern' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::DustBomb,
                'name' => EnemyData::DustBomb->label(),
                'value_hp' => 1200,
                'value_ap' => 30,
                'value_str' => 100,
                'value_def' => 0,
                'value_int' => 0,
                'value_spd' => 0,
                'value_luc' => 0,
                'exp' => 450,
                'drop_money' => 300,
                'portrait_image_path' => EnemyData::DustBomb->image_path(),
                'description' => EnemyData::DustBomb->description(),
                'has_pattern' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::WitherNepenthos,
                'name' => EnemyData::WitherNepenthos->label(),
                'value_hp' => 1200,
                'value_ap' => 100,
                'value_str' => 65,
                'value_def' => 30,
                'value_int' => 110,
                'value_spd' => 80,
                'value_luc' => 0,
                'exp' => 720,
                'drop_money' => 400,
                'portrait_image_path' => EnemyData::WitherNepenthos->image_path(),
                'description' => EnemyData::WitherNepenthos->description(),
                'has_pattern' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::PotDio,
                'name' => EnemyData::PotDio->label(),
                'value_hp' => 1200,
                'value_ap' => 100,
                'value_str' => 55,
                'value_def' => 30,
                'value_int' => 120,
                'value_spd' => 75,
                'value_luc' => 0,
                'exp' => 720,
                'drop_money' => 400,
                'portrait_image_path' => EnemyData::PotDio->image_path(),
                'description' => EnemyData::PotDio->description(),
                'has_pattern' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::GolemBall,
                'name' => EnemyData::GolemBall->label(),
                'value_hp' => 1000,
                'value_ap' => 100,
                'value_str' => 80,
                'value_def' => 100,
                'value_int' => 55,
                'value_spd' => 50,
                'value_luc' => 0,
                'exp' => 750,
                'drop_money' => 420,
                'portrait_image_path' => EnemyData::GolemBall->image_path(),
                'description' => EnemyData::GolemBall->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::Eliminator,
                'name' => EnemyData::Eliminator->label(),
                'value_hp' => 20000,
                'value_ap' => 100,
                'value_str' => 20,
                'value_def' => 0,
                'value_int' => 0,
                'value_spd' => 10,
                'value_luc' => 0,
                'exp' => 500,
                'drop_money' => 250,
                'portrait_image_path' => EnemyData::Eliminator->image_path(),
                'description' => EnemyData::Eliminator->description(),
                'has_pattern' => false, // 攻撃 or ランダムでデバフ技をばら撒く
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::StoneGolem,
                'name' => EnemyData::StoneGolem->label(),
                'value_hp' => 6000,
                'value_ap' => 500,
                'value_str' => 0,
                'value_def' => 50,
                'value_int' => 50,
                'value_spd' => 100,
                'value_luc' => 0,
                'exp' => 2500,
                'drop_money' => 3000,
                'portrait_image_path' => EnemyData::StoneGolem->image_path(),
                'description' => EnemyData::StoneGolem->description(),
                'is_boss' => true,
                'has_pattern' => true,
                'image_aspect_ratio' => '2/1',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // AncientCastle
            [
                'id' => EnemyData::DarkSrara,
                'name' => EnemyData::DarkSrara->label(),
                'value_hp' => 800,
                'value_ap' => 12,
                'value_str' => 80,
                'value_def' => 80,
                'value_int' => 80,
                'value_spd' => 100,
                'value_luc' => 0,
                'exp' => 850,
                'drop_money' => 900,
                'portrait_image_path' => EnemyData::DarkSrara->image_path(),
                'description' => EnemyData::DarkSrara->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::Anima,
                'name' => EnemyData::Anima->label(),
                'value_hp' => 500,
                'value_ap' => 30,
                'value_str' => 50,
                'value_def' => 0,
                'value_int' => 300,
                'value_spd' => 95,
                'value_luc' => 0,
                'exp' => 780,
                'drop_money' => 800,
                'portrait_image_path' => EnemyData::Anima->image_path(),
                'description' => EnemyData::Anima->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::GaiaHand,
                'name' => EnemyData::GaiaHand->label(),
                'value_hp' => 550,
                'value_ap' => 50,
                'value_str' => 200,
                'value_def' => 280,
                'value_int' => 0,
                'value_spd' => 50,
                'value_luc' => 0,
                'exp' => 970,
                'drop_money' => 900,
                'portrait_image_path' => EnemyData::GaiaHand->image_path(),
                'description' => EnemyData::GaiaHand->description(),
                'has_pattern' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::MetalGecko,
                'name' => EnemyData::MetalGecko->label(),
                'value_hp' => 3500,
                'value_ap' => 200,
                'value_str' => 100,
                'value_def' => 200,
                'value_int' => 50,
                'value_spd' => 100,
                'value_luc' => 0,
                'exp' => 3000,
                'drop_money' => 2500,
                'has_pattern' => true,
                'portrait_image_path' => EnemyData::MetalGecko->image_path(),
                'description' => EnemyData::MetalGecko->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::DeathScorpio,
                'name' => EnemyData::DeathScorpio->label(),
                'value_hp' => 800,
                'value_ap' => 20,
                'value_str' => 80,
                'value_def' => 10,
                'value_int' => 10,
                'value_spd' => 70,
                'value_luc' => 800,
                'exp' => 1000,
                'drop_money' => 900,
                'portrait_image_path' => EnemyData::DeathScorpio->image_path(),
                'description' => EnemyData::DeathScorpio->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::Stinger,
                'name' => EnemyData::Stinger->label(),
                'value_hp' => 900,
                'value_ap' => 100,
                'value_str' => 70,
                'value_def' => 10,
                'value_int' => 200,
                'value_spd' => 60,
                'value_luc' => 0,
                'exp' => 970,
                'drop_money' => 900,
                'portrait_image_path' => EnemyData::Stinger->image_path(),
                'description' => EnemyData::Stinger->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::PlasmaBook,
                'name' => EnemyData::PlasmaBook->label(),
                'value_hp' => 1500,
                'value_ap' => 200,
                'value_str' => 85,
                'value_def' => 50,
                'value_int' => 250,
                'value_spd' => 60,
                'value_luc' => 0,
                'exp' => 1200,
                'drop_money' => 900,
                'portrait_image_path' => EnemyData::PlasmaBook->image_path(),
                'description' => EnemyData::PlasmaBook->description(),
                'has_pattern' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::FlareDrago,
                'name' => EnemyData::FlareDrago->label(),
                'value_hp' => 7000,
                'value_ap' => 300,
                'value_str' => 100,
                'value_def' => 150,
                'value_int' => 200,
                'value_spd' => 120,
                'value_luc' => 0,
                'exp' => 5500,
                'drop_money' => 5000,
                'portrait_image_path' => EnemyData::FlareDrago->image_path(),
                'image_aspect_ratio' => '2/1',
                'is_boss' => true,
                'has_pattern' => true,
                'description' => EnemyData::FlareDrago->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::TraitorLordOfDragon,
                'name' => EnemyData::TraitorLordOfDragon->label(),
                // 'value_hp' => 1,
                'value_hp' => 9000,
                'value_ap' => 1000,
                'value_str' => 100,
                'value_def' => 20,
                'value_int' => 300,
                'value_spd' => 130,
                'value_luc' => 100,
                'exp' => 7000,
                'drop_money' => 5500,
                // 'exp' => 0,
                // 'drop_money' => 1,
                'portrait_image_path' => EnemyData::TraitorLordOfDragon->image_path(),
                'image_aspect_ratio' => '2/1',
                'is_boss' => true,
                'has_pattern' => true,
                'description' => EnemyData::TraitorLordOfDragon->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // ボス未実装
            // VastExpanse
            [
                'id' => EnemyData::Celavie,
                'name' => EnemyData::Celavie->label(),
                'value_hp' => 120,
                'value_ap' => 20,
                'value_str' => 40,
                'value_def' => 10,
                'value_int' => 30,
                'value_spd' => 60,
                'value_luc' => 0,
                'exp' => 200,
                'drop_money' => 900,
                'portrait_image_path' => EnemyData::Celavie->image_path(),
                'description' => EnemyData::Celavie->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::GrandCube,
                'name' => EnemyData::GrandCube->label(),
                'value_hp' => 120,
                'value_ap' => 20,
                'value_str' => 40,
                'value_def' => 10,
                'value_int' => 30,
                'value_spd' => 60,
                'value_luc' => 0,
                'exp' => 200,
                'drop_money' => 900,
                'portrait_image_path' => EnemyData::GrandCube->image_path(),
                'description' => EnemyData::GrandCube->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::OriginSlum,
                'name' => EnemyData::OriginSlum->label(),
                'value_hp' => 120,
                'value_ap' => 20,
                'value_str' => 40,
                'value_def' => 10,
                'value_int' => 30,
                'value_spd' => 60,
                'value_luc' => 0,
                'exp' => 200,
                'drop_money' => 900,
                'portrait_image_path' => EnemyData::OriginSlum->image_path(),
                'description' => EnemyData::OriginSlum->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => EnemyData::OriginGwappa,
                'name' => EnemyData::OriginGwappa->label(),
                'value_hp' => 120,
                'value_ap' => 20,
                'value_str' => 40,
                'value_def' => 10,
                'value_int' => 30,
                'value_spd' => 60,
                'value_luc' => 0,
                'exp' => 200,
                'drop_money' => 900,
                'portrait_image_path' => EnemyData::OriginGwappa->image_path(),
                'description' => EnemyData::OriginGwappa->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],

            [
                'id' => EnemyData::HighSrara,
                'name' => EnemyData::HighSrara->label(),
                'value_hp' => 120,
                'value_ap' => 20,
                'value_str' => 40,
                'value_def' => 10,
                'value_int' => 30,
                'value_spd' => 60,
                'value_luc' => 0,
                'exp' => 200,
                'drop_money' => 900,
                'portrait_image_path' => EnemyData::HighSrara->image_path(),
                'description' => EnemyData::HighSrara->description(),
                'created_at' => $now,
                'updated_at' => $now,
            ],

        ];

        foreach ($enemies as $enemy) {
            Enemy::create($enemy);
        }

    }
}
