<?php

namespace Database\Seeders\rpg;

use App\Enums\Rpg\AttackType;
use App\Enums\Rpg\EffectType;
use App\Enums\Rpg\HealType;
use App\Enums\Rpg\ItemData;
use App\Enums\Rpg\TargetRange;
use App\Models\Game\Rpg\Item;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ItemTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        Item::truncate();

        $items = [
            [
                'id' => ItemData::MiniPotion->value,
                'name' => ItemData::MiniPotion->label(),
                'attack_type' => AttackType::NoType->value,
                'heal_type' => HealType::Hp->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::Single->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 15,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 3,
                'price' => 20,
                'description' => ItemData::MiniPotion->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 0,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::Potion->value,
                'name' => ItemData::Potion->label(),
                'attack_type' => AttackType::NoType->value,
                'heal_type' => HealType::Hp->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::Single->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 50,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 5,
                'price' => 100,
                'description' => ItemData::Potion->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 1,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::AllPotion->value,
                'name' => ItemData::AllPotion->label(),
                'attack_type' => AttackType::NoType->value,
                'heal_type' => HealType::Hp->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::All->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 50,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 5,
                'price' => 350,
                'description' => ItemData::AllPotion->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 2,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::HighPotion->value,
                'name' => ItemData::HighPotion->label(),
                'attack_type' => AttackType::NoType->value,
                'heal_type' => HealType::Hp->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::Single->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 100,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 5,
                'price' => 200,
                'description' => ItemData::HighPotion->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 5,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::AllHighPotion->value,
                'name' => ItemData::AllHighPotion->label(),
                'attack_type' => AttackType::NoType->value,
                'heal_type' => HealType::Hp->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::All->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 100,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 5,
                'price' => 650,
                'description' => ItemData::AllHighPotion->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 6,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::LifeElixir->value,
                'name' => ItemData::LifeElixir->label(),
                'attack_type' => AttackType::NoType->value,
                'heal_type' => HealType::Hp->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::Single->value,
                'is_percent_based' => true,
                'percent' => 1.0,
                'fixed_value' => null,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 5,
                'price' => 300,
                'description' => ItemData::LifeElixir->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 6,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::AllLifeElixir->value,
                'name' => ItemData::AllLifeElixir->label(),
                'attack_type' => AttackType::NoType->value,
                'heal_type' => HealType::Hp->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::All->value,
                'is_percent_based' => true,
                'percent' => 1.0,
                'fixed_value' => null,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 5,
                'price' => 1000,
                'description' => ItemData::AllLifeElixir->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 7,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::ResurrectPot->value,
                'name' => ItemData::ResurrectPot->label(),
                'attack_type' => AttackType::NoType->value,
                'heal_type' => HealType::NoType->value,
                'effect_type' => EffectType::Special->value,
                'target_range' => TargetRange::Single->value,
                'is_percent_based' => true,
                'percent' => 0.3,
                'fixed_value' => null,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 3,
                'price' => 300,
                'description' => ItemData::ResurrectPot->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 5,
                'created_at' => $now, 'updated_at' => $now,
            ],

            [
                'id' => ItemData::ManaDrop->value,
                'name' => ItemData::ManaDrop->label(),
                'attack_type' => AttackType::NoType->value,
                'heal_type' => HealType::Ap->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::Single->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 20,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 3,
                'price' => 250,
                'description' => ItemData::ManaDrop->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 1,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::ManaWater->value,
                'name' => ItemData::ManaWater->label(),
                'attack_type' => AttackType::NoType->value,
                'heal_type' => HealType::Ap->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::Single->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 50,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 3,
                'price' => 500,
                'description' => ItemData::ManaWater->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 4,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::ManaElixir->value,
                'name' => ItemData::ManaElixir->label(),
                'attack_type' => AttackType::NoType->value,
                'heal_type' => HealType::Ap->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::Single->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 100,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 2,
                'price' => 1500,
                'description' => ItemData::ManaElixir->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 6,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::FullManaElixir->value,
                'name' => ItemData::FullManaElixir->label(),
                'attack_type' => AttackType::NoType->value,
                'heal_type' => HealType::Ap->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::Single->value,
                'is_percent_based' => true,
                'percent' => 1.0,
                'fixed_value' => null,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 2,
                'price' => 3000,
                'description' => ItemData::FullManaElixir->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 7,
                'created_at' => $now, 'updated_at' => $now,
            ],

            [
                'id' => ItemData::AttackGummy->value,
                'name' => ItemData::AttackGummy->label(),
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 20,
                'buff_turn' => 4,
                'elemental_id' => 0,
                'max_possession_number' => 2,
                'price' => 50,
                'description' => ItemData::AttackGummy->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 1,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::AttackMist->value,
                'name' => ItemData::AttackMist->label(),
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::All->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 20,
                'buff_turn' => 4,
                'elemental_id' => 0,
                'max_possession_number' => 1,
                'price' => 200,
                'description' => ItemData::AttackMist->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 4,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::DefenceGummy->value,
                'name' => ItemData::DefenceGummy->label(),
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 20,
                'buff_turn' => 4,
                'elemental_id' => 0,
                'max_possession_number' => 2,
                'price' => 50,
                'description' => ItemData::DefenceGummy->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 1,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::DefenceMist->value,
                'name' => ItemData::DefenceMist->label(),
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::All->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 20,
                'buff_turn' => 4,
                'elemental_id' => 0,
                'max_possession_number' => 1,
                'price' => 200,
                'description' => ItemData::DefenceMist->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 4,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::IntGummy->value,
                'name' => ItemData::IntGummy->label(),
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 20,
                'buff_turn' => 4,
                'elemental_id' => 0,
                'max_possession_number' => 2,
                'price' => 50,
                'description' => ItemData::IntGummy->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 1,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::IntMist->value,
                'name' => ItemData::IntMist->label(),
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::All->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 20,
                'buff_turn' => 4,
                'elemental_id' => 0,
                'max_possession_number' => 1,
                'price' => 200,
                'description' => ItemData::IntMist->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 4,
                'created_at' => $now, 'updated_at' => $now,
            ],

            [
                'id' => ItemData::MiniBomb->value,
                'name' => ItemData::MiniBomb->label(),
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 150,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 1,
                'price' => 300,
                'description' => ItemData::MiniBomb->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 1,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::Bomb->value,
                'name' => ItemData::Bomb->label(),
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 500,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 1,
                'price' => 1000,
                'description' => ItemData::Bomb->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 4,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::TerminateBomb->value,
                'name' => ItemData::TerminateBomb->label(),
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 500,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 1,
                'price' => 3000,
                'description' => ItemData::TerminateBomb->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 8,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::EtherCapsule->value,
                'name' => ItemData::EtherCapsule->label(),
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 500,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 1,
                'price' => 1000,
                'description' => ItemData::EtherCapsule->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 4,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::EtherCrystal->value,
                'name' => ItemData::EtherCrystal->label(),
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => 500,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 1,
                'price' => 3000,
                'description' => ItemData::EtherCrystal->description(),
                'is_buyable' => true,
                'is_battle_available' => true,
                'required_clears' => 8,
                'created_at' => $now, 'updated_at' => $now,
            ],
            [
                'id' => ItemData::GoldBar->value,
                'name' => ItemData::GoldBar->label(),
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Special->value,
                'target_range' => TargetRange::Self->value,
                'is_percent_based' => false,
                'percent' => null,
                'fixed_value' => null,
                'buff_turn' => null,
                'elemental_id' => 0,
                'max_possession_number' => 3,
                'price' => 60000,
                'description' => ItemData::GoldBar->description(),
                'is_buyable' => false,
                'is_battle_available' => false,
                'created_at' => $now, 'updated_at' => $now,
            ],
        ];

        foreach ($items as $item) {
            Item::create($item);
        }

    }
}
