<?php

namespace Database\Seeders\rpg;

use App\Enums\Rpg\AttackType;
use App\Enums\Rpg\EffectType;
use App\Enums\Rpg\TargetRange;
use App\Models\Game\Rpg\Role;
use App\Models\Game\Rpg\Skill;
use Illuminate\Database\Seeder;

class SkillTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // データベースリセット
        Skill::truncate();

        $seeds = [
            // -------------------- 格闘家 --------------------
            [
                'id' => '10',
                'name' => 'ミドルブロウ',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 6,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => '敵単体に素早く拳を叩き込む。',
            ],
            [
                'id' => '11',
                'name' => 'スピンキック',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => '敵全体に鋭い回転蹴り。',
            ],
            [
                'id' => '12',
                'name' => 'スキル12',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => 'テストスキル',
            ],
            [
                'id' => '13',
                'name' => 'スキル13',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => 'テストスキル',
            ],
            [
                'id' => '14',
                'name' => 'スキル14',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => 'テストスキル',
            ],
            [
                'id' => '15',
                'name' => 'スキル15',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => 'テストスキル',
            ],
            [
                'id' => '16',
                'name' => 'スキル16',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => 'テストスキル',
            ],
            [
                'id' => '17',
                'name' => 'スキル17',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => 'テストスキル',
            ],
            [
                'id' => '18',
                'name' => 'スキル18',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => 'テストスキル',
            ],
            [
                'id' => '19',
                'name' => 'スキル19',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => 'テストスキル',
            ],
            // トランスフォーム、タイタンブレイク

            // -------------------- 治療師 --------------------
            [
                'id' => '20',
                'name' => 'ライフリカバリ',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::Single->value,
                'is_target_enemy' => false,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 5,
                'lv2_percent' => 1.2,
                'lv2_ap_cost' => 6,
                'lv3_percent' => 1.5,
                'lv3_ap_cost' => 7,
                'elemental_id' => 1,
                'description' => '治療師の基本的な回復魔法。味方1人のHPを回復する呪文を唱える。',
            ],
            [
                'id' => '21',
                'name' => 'リカバリオール',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::All->value,
                'is_target_enemy' => false,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 13,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 15,
                'elemental_id' => 1,
                'description' => '回復魔力を周囲に浮かべ、全体のHPを回復する。',
            ],
            [
                'id' => '22',
                'name' => 'ミニボルト',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 3,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 4,
                'elemental_id' => 1,
                'description' => '魔力を敵単体に放つ、治療師の護身用攻撃魔法。',
            ],
            [
                'id' => '23',
                'name' => 'スキル23',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 3,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 4,
                'elemental_id' => 1,
                'description' => '魔力弾を敵単体に放つ攻撃。',
            ],
            [
                'id' => '24',
                'name' => 'スキル24',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 3,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 4,
                'elemental_id' => 1,
                'description' => '魔力弾を敵単体に放つ攻撃。',
            ],
            [
                'id' => '25',
                'name' => 'スキル25',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 3,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 4,
                'elemental_id' => 1,
                'description' => '魔力弾を敵単体に放つ攻撃。',
            ],
            [
                'id' => '26',
                'name' => 'スキル26',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 3,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 4,
                'elemental_id' => 1,
                'description' => '魔力弾を敵単体に放つ攻撃。',
            ],
            [
                'id' => '27',
                'name' => 'スキル27',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 3,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 4,
                'elemental_id' => 1,
                'description' => '魔力弾を敵単体に放つ攻撃。',
            ],
            [
                'id' => '28',
                'name' => 'スキル28',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 3,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 4,
                'elemental_id' => 1,
                'description' => '魔力弾を敵単体に放つ攻撃。',
            ],
            [
                'id' => '29',
                'name' => 'スキル29',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 3,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 4,
                'elemental_id' => 1,
                'description' => '魔力弾を敵単体に放つ攻撃。',
            ],
            // ヘブンレイとかオマージュしたい

            // -------------------- 重騎士 --------------------
            [
                'id' => '30',
                'name' => 'ワイドスラスト',
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 8,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.25,
                'lv3_ap_cost' => 15,
                'elemental_id' => 1,
                'description' => '敵全体を力強く薙ぎ払う。',
            ],
            [
                'id' => '31',
                'name' => 'ワイドガード',
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Special->value,
                'target_range' => TargetRange::All->value,
                'is_target_enemy' => false,
                'is_first' => true,
                'lv1_percent' => 0.3,
                'lv1_ap_cost' => 3,
                'lv1_buff_turn' => 1,
                'lv2_percent' => 0.5,
                'lv2_ap_cost' => 5,
                'lv2_buff_turn' => 1,
                'lv3_percent' => 0.8,
                'lv3_ap_cost' => 5,
                'lv3_buff_turn' => 1,
                'elemental_id' => 1,
                'description' => '先制発動する。使用ターンの味方全員の物理ダメージを軽減する。',
            ],
            [
                'id' => '32',
                'name' => 'ブレイヴスラッシュ',
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 7,
                'lv2_percent' => 1.3,
                'lv2_ap_cost' => 10,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 12,
                'elemental_id' => 1,
                'description' => '敵単体に壮烈の一撃。自分の防御力に依存したダメージを与える。',
            ],
            [
                'id' => '33',
                'name' => 'ガードアップ',
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'is_target_enemy' => false,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方1人の守備力をアップさせる。',
            ],
            [
                'id' => '34',
                'name' => 'スキル34',
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '35',
                'name' => 'スキル35',
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '36',
                'name' => 'スキル36',
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '37',
                'name' => 'スキル37',
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '38',
                'name' => 'スキル38',
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '39',
                'name' => 'スキル39',
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            // ブラッドムーン

            // -------------------- 魔導士 --------------------
            [
                'id' => '40',
                'name' => 'ミニヒール',
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::Single->value,
                'is_target_enemy' => false,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 5,
                'lv2_percent' => 1.2,
                'lv2_ap_cost' => 6,
                'lv3_percent' => 1.5,
                'lv3_ap_cost' => 7,
                'elemental_id' => 1,
                'description' => '味方1人のHPを回復する呪文を唱える。初歩的な回復魔法のひとつ。',
            ],
            [
                'id' => '41',
                'name' => 'ポップヒール',
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::All->value,
                'is_target_enemy' => false,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 13,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 15,
                'elemental_id' => 1,
                'description' => '回復魔力を周囲に浮かべ、全体のHPを回復する。',
            ],
            [
                'id' => '42',
                'name' => 'プチブラスト',
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 3,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 4,
                'elemental_id' => 1,
                'description' => '小さな魔力弾を敵単体に放つ、低コストな攻撃手段。',
            ],
            [
                'id' => '43',
                'name' => 'クラッシュボルト',
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.5,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 2.0,
                'lv2_ap_cost' => 15,
                'lv3_percent' => 3.0,
                'lv3_ap_cost' => 20,
                'elemental_id' => 1,
                'description' => 'マナの塊を撃ち放つ。敵単体に大ダメージ。',
            ],
            [
                'id' => '44',
                'name' => 'マナエクスプロージョン',
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 2.0,
                'lv1_ap_cost' => 40,
                'lv2_percent' => 2.5,
                'lv2_ap_cost' => 50,
                'lv3_percent' => 3.0,
                'lv3_ap_cost' => 60,
                'elemental_id' => 1,
                'description' => '巨大なマナの塊を爆発させ、敵全体に大ダメージを与える。',
            ],
            [
                'id' => '45',
                'name' => 'バトルメイジ',
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Self->value,
                'is_target_enemy' => false,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 30,
                'lv1_buff_turn' => 6,
                'lv2_percent' => 1.5,
                'lv2_ap_cost' => 40,
                'lv2_buff_turn' => 6,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 50,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => '自分の知力を全て力に変換し、STRを飛躍的に上昇させる。',
            ],
            [
                'id' => '46',
                'name' => 'スキル46',
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Self->value,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 30,
                'lv1_buff_turn' => 6,
                'lv2_percent' => 1.5,
                'lv2_ap_cost' => 40,
                'lv2_buff_turn' => 6,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 50,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => '自分の知力を全て力に変換し、STRを飛躍的に上昇させる。',
            ],
            [
                'id' => '47',
                'name' => 'スキル47',
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Self->value,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 30,
                'lv1_buff_turn' => 6,
                'lv2_percent' => 1.5,
                'lv2_ap_cost' => 40,
                'lv2_buff_turn' => 6,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 50,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => '自分の知力を全て力に変換し、STRを飛躍的に上昇させる。',
            ],
            [
                'id' => '48',
                'name' => 'スキル48',
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Self->value,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 30,
                'lv1_buff_turn' => 6,
                'lv2_percent' => 1.5,
                'lv2_ap_cost' => 40,
                'lv2_buff_turn' => 6,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 50,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => '自分の知力を全て力に変換し、STRを飛躍的に上昇させる。',
            ],
            [
                'id' => '49',
                'name' => 'スキル49',
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Self->value,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 30,
                'lv1_buff_turn' => 6,
                'lv2_percent' => 1.5,
                'lv2_ap_cost' => 40,
                'lv2_buff_turn' => 6,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 50,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => '自分の知力を全て力に変換し、STRを飛躍的に上昇させる。',
            ],

            // -------------------- 弓馭者 --------------------
            [
                'id' => '50',
                'name' => 'ブレイクボウガン',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Special->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1,
                'lv1_ap_cost' => 6,
                'lv1_buff_turn' => 2,
                'lv2_percent' => 1.2,
                'lv2_ap_cost' => 8,
                'lv2_buff_turn' => 2,
                'lv3_percent' => 1.5,
                'lv3_ap_cost' => 10,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '敵単体に弩を打ち込みダメージを与え、防御力も低下させる。',
            ],
            [
                'id' => '51',
                'name' => 'ファーストエイド',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::Single->value,
                'is_target_enemy' => false,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 5,
                'lv2_percent' => 2.0,
                'lv2_ap_cost' => 6,
                'lv3_percent' => 3.0,
                'lv3_ap_cost' => 7,
                'elemental_id' => 1,
                'description' => '味方1人の救護を行い、対象のHPを回復する。',
            ],
            [
                'id' => '52',
                'name' => 'ウインドアクセル',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Special->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 6,
                'lv1_buff_turn' => 2,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 7,
                'lv2_buff_turn' => 2,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 8,
                'lv3_buff_turn' => 2,
                'elemental_id' => 1,
                'description' => '敵単体を攻撃しつつ、次のターンの素早さを上げる。',
            ],
            [
                'id' => '53',
                'name' => 'スキル53',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 6,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => '説明',
            ],
            [
                'id' => '54',
                'name' => 'スキル54',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 6,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => '説明',
            ],
            [
                'id' => '55',
                'name' => 'スキル55',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 6,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => '説明',
            ],
            [
                'id' => '56',
                'name' => 'スキル56',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 6,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => '説明',
            ],
            [
                'id' => '57',
                'name' => 'スキル57',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 6,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => '説明',
            ],
            [
                'id' => '58',
                'name' => 'スキル58',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 6,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => '説明',
            ],
            [
                'id' => '59',
                'name' => 'スキル59',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 6,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => '説明',
            ],

            // -------------------- 理術士 --------------------
            [
                'id' => '60',
                'name' => 'ガードスペル',
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'is_target_enemy' => false,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 4,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 5,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => '味方1人の守備力をアップさせる。',
            ],
            [
                'id' => '61',
                'name' => 'アタックスペル',
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'is_target_enemy' => false,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 4,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 5,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => '味方1人の攻撃力をアップさせる。',
            ],
            [
                'id' => '62',
                'name' => 'マジックスペル',
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'is_target_enemy' => false,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 4,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 5,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => '味方1人の魔力をアップさせる。',
            ],
            [
                'id' => '63',
                'name' => 'ブックスマッシュ',
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 4,
                'lv2_percent' => 1.5,
                'lv2_ap_cost' => 6,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 8,
                'elemental_id' => 1,
                'description' => '手持ちの魔導書を用いて、敵単体を全力でぶん殴る。',
            ],
            [
                'id' => '64',
                'name' => 'スキル64',
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '65',
                'name' => 'スキル65',
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '66',
                'name' => 'スキル66',
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '67',
                'name' => 'スキル67',
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '68',
                'name' => 'スキル68',
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '69',
                'name' => 'スキル69',
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],

            // 敵の使用するスキル 100番以降

        ];

        foreach ($seeds as $seed) {
            Skill::create($seed);
        }

    }
}
