<?php

namespace Database\Seeders\rpg;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Game\Rpg\Skill;
use App\Models\Game\Rpg\Role;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class SkillTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    public function run(): void
    {
      $now = Carbon::now();

      // データベースリセット
      Skill::truncate();

      $skills = [
        // 格闘家スキル
        [
          'id' => '10',
          'name' => 'ミドルブロウ',
          'available_role_id' => Role::ROLE_STRIKER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 1.2,
          'lv1_ap_cost' => 6,
          'lv2_percent' => 1.4,
          'lv2_ap_cost' => 8,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 10,
          'elemental_id' => 1,
          'description' => '敵単体に素早く拳を叩き込む。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '11',
          'name' => 'スピンキック',
          'available_role_id' => Role::ROLE_STRIKER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_ALL,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 10,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 12,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 16,
          'elemental_id' => 1,
          'description' => '敵全体に鋭い回転蹴り。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '12',
          'name' => 'スキル12',
          'available_role_id' => Role::ROLE_STRIKER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_ALL,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 10,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 12,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 16,
          'elemental_id' => 1,
          'description' => 'テストスキル',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '13',
          'name' => 'スキル13',
          'available_role_id' => Role::ROLE_STRIKER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_ALL,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 10,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 12,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 16,
          'elemental_id' => 1,
          'description' => 'テストスキル',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '14',
          'name' => 'スキル14',
          'available_role_id' => Role::ROLE_STRIKER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_ALL,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 10,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 12,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 16,
          'elemental_id' => 1,
          'description' => 'テストスキル',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '15',
          'name' => 'スキル15',
          'available_role_id' => Role::ROLE_STRIKER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_ALL,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 10,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 12,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 16,
          'elemental_id' => 1,
          'description' => 'テストスキル',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '16',
          'name' => 'スキル16',
          'available_role_id' => Role::ROLE_STRIKER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_ALL,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 10,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 12,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 16,
          'elemental_id' => 1,
          'description' => 'テストスキル',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '17',
          'name' => 'スキル17',
          'available_role_id' => Role::ROLE_STRIKER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_ALL,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 10,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 12,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 16,
          'elemental_id' => 1,
          'description' => 'テストスキル',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '18',
          'name' => 'スキル18',
          'available_role_id' => Role::ROLE_STRIKER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_ALL,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 10,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 12,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 16,
          'elemental_id' => 1,
          'description' => 'テストスキル',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '19',
          'name' => 'スキル19',
          'available_role_id' => Role::ROLE_STRIKER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_ALL,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 10,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 12,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 16,
          'elemental_id' => 1,
          'description' => 'テストスキル',
          'created_at' => $now,
          'updated_at' => $now
        ],
        // トランスフォーム、タイタンブレイク



        // 治療師スキル
        [
          'id' => '20',
          'name' => 'メディヒール',
          'available_role_id' => Role::ROLE_MEDIC,
          'attack_type' => Skill::ATTACK_MAGIC_TYPE,
          'effect_type' => Skill::EFFECT_HEAL_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 1.0,
          'lv1_ap_cost' => 5,
          'lv2_percent' => 1.2,
          'lv2_ap_cost' => 6,
          'lv3_percent' => 1.5,
          'lv3_ap_cost' => 7,
          'elemental_id' => 1,
          'description' => '味方1人のHPを回復する呪文を唱える。初歩的な回復魔法のひとつ。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '21',
          'name' => 'メディエリアヒール',
          'available_role_id' => Role::ROLE_MEDIC,
          'attack_type' => Skill::ATTACK_MAGIC_TYPE,
          'effect_type' => Skill::EFFECT_HEAL_TYPE,
          'target_range' => Skill::TARGET_RANGE_ALL,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 10,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 13,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 15,
          'elemental_id' => 1,
          'description' => '回復魔力を周囲に浮かべ、全体のHPを回復する。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '22',
          'name' => 'メディブラスト',
          'available_role_id' => Role::ROLE_MEDIC,
          'attack_type' => Skill::ATTACK_MAGIC_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 3,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 3,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 4,
          'elemental_id' => 1,
          'description' => '魔力弾を敵単体に放つ攻撃。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '23',
          'name' => 'スキル23',
          'available_role_id' => Role::ROLE_MEDIC,
          'attack_type' => Skill::ATTACK_MAGIC_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 3,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 3,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 4,
          'elemental_id' => 1,
          'description' => '魔力弾を敵単体に放つ攻撃。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '24',
          'name' => 'スキル24',
          'available_role_id' => Role::ROLE_MEDIC,
          'attack_type' => Skill::ATTACK_MAGIC_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 3,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 3,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 4,
          'elemental_id' => 1,
          'description' => '魔力弾を敵単体に放つ攻撃。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '25',
          'name' => 'スキル25',
          'available_role_id' => Role::ROLE_MEDIC,
          'attack_type' => Skill::ATTACK_MAGIC_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 3,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 3,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 4,
          'elemental_id' => 1,
          'description' => '魔力弾を敵単体に放つ攻撃。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '26',
          'name' => 'スキル26',
          'available_role_id' => Role::ROLE_MEDIC,
          'attack_type' => Skill::ATTACK_MAGIC_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 3,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 3,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 4,
          'elemental_id' => 1,
          'description' => '魔力弾を敵単体に放つ攻撃。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '27',
          'name' => 'スキル27',
          'available_role_id' => Role::ROLE_MEDIC,
          'attack_type' => Skill::ATTACK_MAGIC_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 3,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 3,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 4,
          'elemental_id' => 1,
          'description' => '魔力弾を敵単体に放つ攻撃。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '28',
          'name' => 'スキル28',
          'available_role_id' => Role::ROLE_MEDIC,
          'attack_type' => Skill::ATTACK_MAGIC_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 3,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 3,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 4,
          'elemental_id' => 1,
          'description' => '魔力弾を敵単体に放つ攻撃。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '29',
          'name' => 'スキル29',
          'available_role_id' => Role::ROLE_MEDIC,
          'attack_type' => Skill::ATTACK_MAGIC_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 3,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 3,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 4,
          'elemental_id' => 1,
          'description' => '魔力弾を敵単体に放つ攻撃。',
          'created_at' => $now,
          'updated_at' => $now
        ],



        // 重騎士スキル
        [
          'id' => '30',
          'name' => 'ワイドスラスト',
          'available_role_id' => Role::ROLE_PARADIN,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_ALL,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 8,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 12,
          'lv3_percent' => 1.25,
          'lv3_ap_cost' => 15,
          'elemental_id' => 1,
          'description' => '敵全体を力強く薙ぎ払う。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '31',
          'name' => 'ワイドガード',
          'available_role_id' => Role::ROLE_PARADIN,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_SPECIAL_TYPE,
          'target_range' => Skill::TARGET_RANGE_ALL,
          'lv1_percent' => 0.3,
          'lv1_ap_cost' => 3,
          'lv1_buff_turn' => 1,
          'lv2_percent' => 0.5,
          'lv2_ap_cost' => 5,
          'lv2_buff_turn' => 1,
          'lv3_percent' => 0.8,
          'lv3_ap_cost' => 5,
          'lv3_buff_turn' => 1,
          'elemental_id' => 1,
          'description' => '使用ターンの味方全員の物理ダメージを軽減する。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '32',
          'name' => 'ブレイヴスラッシュ',
          'available_role_id' => Role::ROLE_PARADIN,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 1.0,
          'lv1_ap_cost' => 7,
          'lv2_percent' => 1.3,
          'lv2_ap_cost' => 10,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 12,
          'elemental_id' => 1,
          'description' => '敵単体に壮烈の一撃。自分の防御力に依存したダメージを与える。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '33',
          'name' => 'ガードアップ',
          'available_role_id' => Role::ROLE_PARADIN,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '34',
          'name' => 'スキル34',
          'available_role_id' => Role::ROLE_PARADIN,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '35',
          'name' => 'スキル35',
          'available_role_id' => Role::ROLE_PARADIN,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '36',
          'name' => 'スキル36',
          'available_role_id' => Role::ROLE_PARADIN,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '37',
          'name' => 'スキル37',
          'available_role_id' => Role::ROLE_PARADIN,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '38',
          'name' => 'スキル38',
          'available_role_id' => Role::ROLE_PARADIN,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '39',
          'name' => 'スキル39',
          'available_role_id' => Role::ROLE_PARADIN,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        // ブラッドムーン



        // 魔導士スキル
        [
          'id' => '40',
          'name' => 'ミニヒール',
          'available_role_id' => Role::ROLE_MAGE,
          'attack_type' => Skill::ATTACK_MAGIC_TYPE,
          'effect_type' => Skill::EFFECT_HEAL_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 1.0,
          'lv1_ap_cost' => 5,
          'lv2_percent' => 1.2,
          'lv2_ap_cost' => 6,
          'lv3_percent' => 1.5,
          'lv3_ap_cost' => 7,
          'elemental_id' => 1,
          'description' => '味方1人のHPを回復する呪文を唱える。初歩的な回復魔法のひとつ。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '41',
          'name' => 'ポップヒール',
          'available_role_id' => Role::ROLE_MAGE,
          'attack_type' => Skill::ATTACK_MAGIC_TYPE,
          'effect_type' => Skill::EFFECT_HEAL_TYPE,
          'target_range' => Skill::TARGET_RANGE_ALL,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 10,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 13,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 15,
          'elemental_id' => 1,
          'description' => '回復魔力を周囲に浮かべ、全体のHPを回復する。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '42',
          'name' => 'プチブラスト',
          'available_role_id' => Role::ROLE_MAGE,
          'attack_type' => Skill::ATTACK_MAGIC_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.8,
          'lv1_ap_cost' => 3,
          'lv2_percent' => 1.0,
          'lv2_ap_cost' => 3,
          'lv3_percent' => 1.3,
          'lv3_ap_cost' => 4,
          'elemental_id' => 1,
          'description' => '小さな魔力弾を敵単体に放つ、低コストな攻撃手段。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '43',
          'name' => 'クラッシュボルト',
          'available_role_id' => Role::ROLE_MAGE,
          'attack_type' => Skill::ATTACK_MAGIC_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 1.5,
          'lv1_ap_cost' => 10,
          'lv2_percent' => 2.0,
          'lv2_ap_cost' => 15,
          'lv3_percent' => 3.0,
          'lv3_ap_cost' => 20,
          'elemental_id' => 1,
          'description' => 'マナの塊を撃ち放つ。敵単体に大ダメージ。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '44',
          'name' => 'マナエクスプロージョン',
          'available_role_id' => Role::ROLE_MAGE,
          'attack_type' => Skill::ATTACK_MAGIC_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_ALL,
          'lv1_percent' => 2.0,
          'lv1_ap_cost' => 40,
          'lv2_percent' => 2.5,
          'lv2_ap_cost' => 50,
          'lv3_percent' => 3.0,
          'lv3_ap_cost' => 60,
          'elemental_id' => 1,
          'description' => '巨大なマナの塊を爆発させ、敵全体に大ダメージを与える。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '45',
          'name' => 'バトルメイジ',
          'available_role_id' => Role::ROLE_MAGE,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SELF,
          'lv1_percent' => 1.0,
          'lv1_ap_cost' => 30,
          'lv1_buff_turn' => 6,
          'lv2_percent' => 1.5,
          'lv2_ap_cost' => 40,
          'lv2_buff_turn' => 6,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 50,
          'lv3_buff_turn' => 6,
          'elemental_id' => 1,
          'description' => '自分の知力を全て力に変換し、STRを飛躍的に上昇させる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '46',
          'name' => 'スキル46',
          'available_role_id' => Role::ROLE_MAGE,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SELF,
          'lv1_percent' => 1.0,
          'lv1_ap_cost' => 30,
          'lv1_buff_turn' => 6,
          'lv2_percent' => 1.5,
          'lv2_ap_cost' => 40,
          'lv2_buff_turn' => 6,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 50,
          'lv3_buff_turn' => 6,
          'elemental_id' => 1,
          'description' => '自分の知力を全て力に変換し、STRを飛躍的に上昇させる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '47',
          'name' => 'スキル47',
          'available_role_id' => Role::ROLE_MAGE,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SELF,
          'lv1_percent' => 1.0,
          'lv1_ap_cost' => 30,
          'lv1_buff_turn' => 6,
          'lv2_percent' => 1.5,
          'lv2_ap_cost' => 40,
          'lv2_buff_turn' => 6,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 50,
          'lv3_buff_turn' => 6,
          'elemental_id' => 1,
          'description' => '自分の知力を全て力に変換し、STRを飛躍的に上昇させる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '48',
          'name' => 'スキル48',
          'available_role_id' => Role::ROLE_MAGE,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SELF,
          'lv1_percent' => 1.0,
          'lv1_ap_cost' => 30,
          'lv1_buff_turn' => 6,
          'lv2_percent' => 1.5,
          'lv2_ap_cost' => 40,
          'lv2_buff_turn' => 6,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 50,
          'lv3_buff_turn' => 6,
          'elemental_id' => 1,
          'description' => '自分の知力を全て力に変換し、STRを飛躍的に上昇させる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '49',
          'name' => 'スキル49',
          'available_role_id' => Role::ROLE_MAGE,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SELF,
          'lv1_percent' => 1.0,
          'lv1_ap_cost' => 30,
          'lv1_buff_turn' => 6,
          'lv2_percent' => 1.5,
          'lv2_ap_cost' => 40,
          'lv2_buff_turn' => 6,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 50,
          'lv3_buff_turn' => 6,
          'elemental_id' => 1,
          'description' => '自分の知力を全て力に変換し、STRを飛躍的に上昇させる。',
          'created_at' => $now,
          'updated_at' => $now
        ],


        // 弓馭者スキル
        [
          'id' => '50',
          'name' => 'ブレイクボウガン',
          'available_role_id' => Role::ROLE_RANGER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 1.2,
          'lv1_ap_cost' => 6,
          'lv2_percent' => 1.4,
          'lv2_ap_cost' => 8,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 10,
          'elemental_id' => 1,
          'description' => '敵単体に弩を打ち込み、ダメージを与えつつ物理防御力も低下させる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '51',
          'name' => 'スキル51',
          'available_role_id' => Role::ROLE_RANGER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 1.2,
          'lv1_ap_cost' => 6,
          'lv2_percent' => 1.4,
          'lv2_ap_cost' => 8,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 10,
          'elemental_id' => 1,
          'description' => '説明',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '52',
          'name' => 'スキル52',
          'available_role_id' => Role::ROLE_RANGER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 1.2,
          'lv1_ap_cost' => 6,
          'lv2_percent' => 1.4,
          'lv2_ap_cost' => 8,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 10,
          'elemental_id' => 1,
          'description' => '説明',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '53',
          'name' => 'スキル53',
          'available_role_id' => Role::ROLE_RANGER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 1.2,
          'lv1_ap_cost' => 6,
          'lv2_percent' => 1.4,
          'lv2_ap_cost' => 8,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 10,
          'elemental_id' => 1,
          'description' => '説明',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '54',
          'name' => 'スキル54',
          'available_role_id' => Role::ROLE_RANGER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 1.2,
          'lv1_ap_cost' => 6,
          'lv2_percent' => 1.4,
          'lv2_ap_cost' => 8,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 10,
          'elemental_id' => 1,
          'description' => '説明',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '55',
          'name' => 'スキル55',
          'available_role_id' => Role::ROLE_RANGER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 1.2,
          'lv1_ap_cost' => 6,
          'lv2_percent' => 1.4,
          'lv2_ap_cost' => 8,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 10,
          'elemental_id' => 1,
          'description' => '説明',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '56',
          'name' => 'スキル56',
          'available_role_id' => Role::ROLE_RANGER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 1.2,
          'lv1_ap_cost' => 6,
          'lv2_percent' => 1.4,
          'lv2_ap_cost' => 8,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 10,
          'elemental_id' => 1,
          'description' => '説明',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '57',
          'name' => 'スキル57',
          'available_role_id' => Role::ROLE_RANGER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 1.2,
          'lv1_ap_cost' => 6,
          'lv2_percent' => 1.4,
          'lv2_ap_cost' => 8,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 10,
          'elemental_id' => 1,
          'description' => '説明',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '58',
          'name' => 'スキル58',
          'available_role_id' => Role::ROLE_RANGER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 1.2,
          'lv1_ap_cost' => 6,
          'lv2_percent' => 1.4,
          'lv2_ap_cost' => 8,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 10,
          'elemental_id' => 1,
          'description' => '説明',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '59',
          'name' => 'スキル59',
          'available_role_id' => Role::ROLE_RANGER,
          'attack_type' => Skill::ATTACK_PHYSICAL_TYPE,
          'effect_type' => Skill::EFFECT_DAMAGE_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 1.2,
          'lv1_ap_cost' => 6,
          'lv2_percent' => 1.4,
          'lv2_ap_cost' => 8,
          'lv3_percent' => 2.0,
          'lv3_ap_cost' => 10,
          'elemental_id' => 1,
          'description' => '説明',
          'created_at' => $now,
          'updated_at' => $now
        ],


        // 理術士スキル
        [
          'id' => '60',
          'name' => 'ガードスペル',
          'available_role_id' => Role::ROLE_BUFFER,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '61',
          'name' => 'スキル61',
          'available_role_id' => Role::ROLE_BUFFER,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '62',
          'name' => 'スキル62',
          'available_role_id' => Role::ROLE_BUFFER,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '63',
          'name' => 'スキル63',
          'available_role_id' => Role::ROLE_BUFFER,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '64',
          'name' => 'スキル64',
          'available_role_id' => Role::ROLE_BUFFER,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '65',
          'name' => 'スキル65',
          'available_role_id' => Role::ROLE_BUFFER,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '66',
          'name' => 'スキル66',
          'available_role_id' => Role::ROLE_BUFFER,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '67',
          'name' => 'スキル67',
          'available_role_id' => Role::ROLE_BUFFER,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '68',
          'name' => 'スキル68',
          'available_role_id' => Role::ROLE_BUFFER,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],
        [
          'id' => '69',
          'name' => 'スキル69',
          'available_role_id' => Role::ROLE_BUFFER,
          'attack_type' => Skill::ATTACK_NO_TYPE,
          'effect_type' => Skill::EFFECT_BUFF_TYPE,
          'target_range' => Skill::TARGET_RANGE_SINGLE,
          'lv1_percent' => 0.5,
          'lv1_ap_cost' => 2,
          'lv1_buff_turn' => 3,
          'lv2_percent' => 0.7,
          'lv2_ap_cost' => 2,
          'lv2_buff_turn' => 3,
          'lv3_percent' => 1.0,
          'lv3_ap_cost' => 2,
          'lv3_buff_turn' => 3,
          'elemental_id' => 1,
          'description' => '味方単体の守備力をアップさせる。',
          'created_at' => $now,
          'updated_at' => $now
        ],

        // 敵の使用するスキル 100番以降

      ];

      foreach ($skills as $skill) {
        Skill::create($skill);
      }


    }
}
