<?php

namespace Database\Seeders\rpg;

use App\Enums\Rpg\AttackType;
use App\Enums\Rpg\EffectType;
use App\Enums\Rpg\SkillDefinition;
use App\Enums\Rpg\TargetRange;
use App\Models\Game\Rpg\Role;
use App\Models\Game\Rpg\Skill;
use Illuminate\Database\Seeder;

class SkillTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // データベースリセット
        Skill::truncate();

        $seeds = [
            // -------------------- 格闘家 --------------------
            [
                'id' => SkillDefinition::MiddleBlow->value,
                'name' => SkillDefinition::MiddleBlow->label(),
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 5,
                'lv2_percent' => 1.5,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => SkillDefinition::MiddleBlow->description(),
            ],
            [
                'id' => SkillDefinition::HeavyKnuckle->value,
                'name' => SkillDefinition::HeavyKnuckle->label(),
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Special->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 8,
                'lv2_percent' => 2.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 3.5,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => SkillDefinition::HeavyKnuckle->description(),
            ],
            [
                'id' => SkillDefinition::SpinKick->value,
                'name' => SkillDefinition::SpinKick->label(),
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 8,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 10,
                'lv3_percent' => 1.5,
                'lv3_ap_cost' => 15,
                'elemental_id' => 1,
                'description' => SkillDefinition::SpinKick->description(),
            ],
            [
                'id' => SkillDefinition::Transform->value,
                'name' => SkillDefinition::Transform->label(),
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Self->value,
                'is_target_enemy' => false,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 30,
                'lv1_buff_turn' => 6,
                'lv2_percent' => 1.5,
                'lv2_ap_cost' => 40,
                'lv2_buff_turn' => 6,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 50,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => SkillDefinition::Transform->description(),
            ],
            /*
            [
                'id' => '12',
                'name' => 'スキル12',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => 'テストスキル',
            ],
            [
                'id' => '13',
                'name' => 'スキル13',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => 'テストスキル',
            ],
            [
                'id' => '14',
                'name' => 'スキル14',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => 'テストスキル',
            ],
            [
                'id' => '15',
                'name' => 'スキル15',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => 'テストスキル',
            ],
            [
                'id' => '16',
                'name' => 'スキル16',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => 'テストスキル',
            ],
            [
                'id' => '17',
                'name' => 'スキル17',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => 'テストスキル',
            ],
            [
                'id' => '18',
                'name' => 'スキル18',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => 'テストスキル',
            ],
            [
                'id' => '19',
                'name' => 'スキル19',
                'available_role_id' => Role::ROLE_STRIKER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 16,
                'elemental_id' => 1,
                'description' => 'テストスキル',
            ],
            */
            // タイタンブレイク
            // 必ず後攻になるが、そのぶんすごいダメージみたいな感じで欲しい

            // -------------------- 治療師 --------------------
            [
                'id' => SkillDefinition::Healing->value,
                'name' => SkillDefinition::Healing->label(),
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::Single->value,
                'is_target_enemy' => false,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 5,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 7,
                'lv3_percent' => 1.5,
                'lv3_ap_cost' => 8,
                'elemental_id' => 1,
                'description' => SkillDefinition::Healing->description(),
            ],
            [
                'id' => SkillDefinition::AllHealing->value,
                'name' => SkillDefinition::AllHealing->label(),
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::All->value,
                'is_target_enemy' => false,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 0.8,
                'lv2_ap_cost' => 13,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 15,
                'elemental_id' => 1,
                'description' => SkillDefinition::AllHealing->description(),
            ],
            [
                'id' => SkillDefinition::MiniBolt->value,
                'name' => SkillDefinition::MiniBolt->label(),
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 5,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 7,
                'lv3_percent' => 1.2,
                'lv3_ap_cost' => 8,
                'elemental_id' => 1,
                'description' => SkillDefinition::MiniBolt->description(),
            ],
            /*
            [
                'id' => '23',
                'name' => 'スキル23',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 3,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 4,
                'elemental_id' => 1,
                'description' => '魔力弾を敵単体に放つ攻撃。',
            ],
            [
                'id' => '24',
                'name' => 'スキル24',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 3,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 4,
                'elemental_id' => 1,
                'description' => '魔力弾を敵単体に放つ攻撃。',
            ],
            [
                'id' => '25',
                'name' => 'スキル25',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 3,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 4,
                'elemental_id' => 1,
                'description' => '魔力弾を敵単体に放つ攻撃。',
            ],
            [
                'id' => '26',
                'name' => 'スキル26',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 3,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 4,
                'elemental_id' => 1,
                'description' => '魔力弾を敵単体に放つ攻撃。',
            ],
            [
                'id' => '27',
                'name' => 'スキル27',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 3,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 4,
                'elemental_id' => 1,
                'description' => '魔力弾を敵単体に放つ攻撃。',
            ],
            [
                'id' => '28',
                'name' => 'スキル28',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 3,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 4,
                'elemental_id' => 1,
                'description' => '魔力弾を敵単体に放つ攻撃。',
            ],
            [
                'id' => '29',
                'name' => 'スキル29',
                'available_role_id' => Role::ROLE_MEDIC,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 3,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 4,
                'elemental_id' => 1,
                'description' => '魔力弾を敵単体に放つ攻撃。',
            ],
            */
            // ヘブンレイとかオマージュしたい

            // -------------------- 重騎士 --------------------
            [
                'id' => SkillDefinition::WideThrust->value,
                'name' => SkillDefinition::WideThrust->label(),
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 0.8,
                'lv1_ap_cost' => 6,
                'lv2_percent' => 1.0,
                'lv2_ap_cost' => 9,
                'lv3_percent' => 1.3,
                'lv3_ap_cost' => 12,
                'elemental_id' => 1,
                'description' => SkillDefinition::WideThrust->description(),
            ],
            [
                'id' => SkillDefinition::WideGuard->value,
                'name' => SkillDefinition::WideGuard->label(),
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Special->value,
                'target_range' => TargetRange::All->value,
                'is_target_enemy' => false,
                'is_first' => true,
                'lv1_percent' => 0.2,
                'lv1_ap_cost' => 3,
                'lv1_buff_turn' => 1,
                'lv2_percent' => 0.3,
                'lv2_ap_cost' => 6,
                'lv2_buff_turn' => 1,
                'lv3_percent' => 0.5,
                'lv3_ap_cost' => 9,
                'lv3_buff_turn' => 1,
                'elemental_id' => 1,
                'description' => SkillDefinition::WideGuard->description(),
            ],
            [
                'id' => SkillDefinition::BraveSlash->value,
                'name' => SkillDefinition::BraveSlash->label(),
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 8,
                'lv2_percent' => 1.3,
                'lv2_ap_cost' => 12,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 15,
                'elemental_id' => 1,
                'description' => SkillDefinition::BraveSlash->description(),
            ],
            [
                'id' => SkillDefinition::GuardUp->value,
                'name' => SkillDefinition::GuardUp->label(),
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'is_target_enemy' => false,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 5,
                'lv1_buff_turn' => 4,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 7,
                'lv2_buff_turn' => 4,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 10,
                'lv3_buff_turn' => 5,
                'elemental_id' => 1,
                'description' => SkillDefinition::GuardUp->description(),
            ],
            /*
            [
                'id' => '34',
                'name' => 'スキル34',
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '35',
                'name' => 'スキル35',
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '36',
                'name' => 'スキル36',
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '37',
                'name' => 'スキル37',
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '38',
                'name' => 'スキル38',
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '39',
                'name' => 'スキル39',
                'available_role_id' => Role::ROLE_PALADIN,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            */
            // ブラッドムーン

            // -------------------- 魔導師 --------------------
            [
                'id' => SkillDefinition::MiniHeal->value,
                'name' => SkillDefinition::MiniHeal->label(),
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::Single->value,
                'is_target_enemy' => false,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 10,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 15,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 20,
                'elemental_id' => 1,
                'description' => SkillDefinition::MiniHeal->description(),
            ],
            [
                'id' => SkillDefinition::PopHeal->value,
                'name' => SkillDefinition::PopHeal->label(),
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::All->value,
                'is_target_enemy' => false,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 20,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 30,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 40,
                'elemental_id' => 1,
                'description' => SkillDefinition::PopHeal->description(),
            ],
            [
                'id' => SkillDefinition::PetitBlast->value,
                'name' => SkillDefinition::PetitBlast->label(),
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 5,
                'lv2_percent' => 1.2,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 1.5,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => SkillDefinition::PetitBlast->description(),
            ],
            [
                'id' => SkillDefinition::CrashBolt->value,
                'name' => SkillDefinition::CrashBolt->label(),
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.5,
                'lv1_ap_cost' => 15,
                'lv2_percent' => 2.0,
                'lv2_ap_cost' => 20,
                'lv3_percent' => 3.0,
                'lv3_ap_cost' => 25,
                'elemental_id' => 1,
                'description' => SkillDefinition::CrashBolt->description(),
            ],
            [
                'id' => SkillDefinition::ManaExplosion->value,
                'name' => SkillDefinition::ManaExplosion->label(),
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::All->value,
                'lv1_percent' => 1.5,
                'lv1_ap_cost' => 30,
                'lv2_percent' => 2.0,
                'lv2_ap_cost' => 40,
                'lv3_percent' => 3.0,
                'lv3_ap_cost' => 50,
                'elemental_id' => 1,
                'description' => SkillDefinition::ManaExplosion->description(),
            ],
            [
                'id' => SkillDefinition::BattleMage->value,
                'name' => SkillDefinition::BattleMage->label(),
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Self->value,
                'is_target_enemy' => false,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 30,
                'lv1_buff_turn' => 6,
                'lv2_percent' => 1.5,
                'lv2_ap_cost' => 40,
                'lv2_buff_turn' => 6,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 50,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => SkillDefinition::BattleMage->description(),
            ],
            /*
            [
                'id' => '46',
                'name' => 'スキル46',
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Self->value,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 30,
                'lv1_buff_turn' => 6,
                'lv2_percent' => 1.5,
                'lv2_ap_cost' => 40,
                'lv2_buff_turn' => 6,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 50,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => '自分の知力を全て力に変換し、STRを飛躍的に上昇させる。',
            ],
            [
                'id' => '47',
                'name' => 'スキル47',
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Self->value,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 30,
                'lv1_buff_turn' => 6,
                'lv2_percent' => 1.5,
                'lv2_ap_cost' => 40,
                'lv2_buff_turn' => 6,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 50,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => '自分の知力を全て力に変換し、STRを飛躍的に上昇させる。',
            ],
            [
                'id' => '48',
                'name' => 'スキル48',
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Self->value,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 30,
                'lv1_buff_turn' => 6,
                'lv2_percent' => 1.5,
                'lv2_ap_cost' => 40,
                'lv2_buff_turn' => 6,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 50,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => '自分の知力を全て力に変換し、STRを飛躍的に上昇させる。',
            ],
            [
                'id' => '49',
                'name' => 'スキル49',
                'available_role_id' => Role::ROLE_MAGE,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Self->value,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 30,
                'lv1_buff_turn' => 6,
                'lv2_percent' => 1.5,
                'lv2_ap_cost' => 40,
                'lv2_buff_turn' => 6,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 50,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => '自分の知力を全て力に変換し、STRを飛躍的に上昇させる。',
            ],
            */

            // -------------------- 弓馭者 --------------------
            [
                'id' => SkillDefinition::FirstAid->value,
                'name' => SkillDefinition::FirstAid->label(),
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::Single->value,
                'is_target_enemy' => false,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 5,
                'lv2_percent' => 2.5,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 5.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => SkillDefinition::FirstAid->description(),
            ],
            [
                'id' => SkillDefinition::FairyFog->value,
                'name' => SkillDefinition::FairyFog->label(),
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Heal->value,
                'target_range' => TargetRange::All->value,
                'is_target_enemy' => false,
                'lv1_percent' => 1.0,
                'lv1_ap_cost' => 15,
                'lv2_percent' => 1.5,
                'lv2_ap_cost' => 20,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 25,
                'elemental_id' => 1,
                'description' => SkillDefinition::FairyFog->description(),
            ],
            [
                'id' => SkillDefinition::BreakBowGun->value,
                'name' => SkillDefinition::BreakBowGun->label(),
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Special->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1,
                'lv1_ap_cost' => 6,
                'lv1_buff_turn' => 1,
                'lv2_percent' => 1.2,
                'lv2_ap_cost' => 8,
                'lv2_buff_turn' => 1,
                'lv3_percent' => 1.5,
                'lv3_ap_cost' => 10,
                'lv3_buff_turn' => 2,
                'elemental_id' => 1,
                'description' => SkillDefinition::BreakBowGun->description(),
            ],
            [
                'id' => SkillDefinition::WindAccel->value,
                'name' => SkillDefinition::WindAccel->label(),
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Special->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 4,
                'lv1_buff_turn' => 2,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 6,
                'lv2_buff_turn' => 2,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 8,
                'lv3_buff_turn' => 2,
                'elemental_id' => 1,
                'description' => SkillDefinition::WindAccel->description(),
            ],
            /*
            [
                'id' => '53',
                'name' => 'スキル53',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 6,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => '説明',
            ],
            [
                'id' => '54',
                'name' => 'スキル54',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 6,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => '説明',
            ],
            [
                'id' => '55',
                'name' => 'スキル55',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 6,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => '説明',
            ],
            [
                'id' => '56',
                'name' => 'スキル56',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 6,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => '説明',
            ],
            [
                'id' => '57',
                'name' => 'スキル57',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 6,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => '説明',
            ],
            [
                'id' => '58',
                'name' => 'スキル58',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 6,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => '説明',
            ],
            [
                'id' => '59',
                'name' => 'スキル59',
                'available_role_id' => Role::ROLE_RANGER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 6,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 8,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => '説明',
            ],
            */

            // -------------------- 理術師 --------------------
            [
                'id' => SkillDefinition::BookSmash->value,
                'name' => SkillDefinition::BookSmash->label(),
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::Physical->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 3,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 5,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 8,
                'elemental_id' => 1,
                'description' => SkillDefinition::BookSmash->description(),
            ],
            [
                'id' => SkillDefinition::MagicMissile->value,
                'name' => SkillDefinition::MagicMissile->label(),
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::Magic->value,
                'effect_type' => EffectType::Damage->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 1.2,
                'lv1_ap_cost' => 4,
                'lv2_percent' => 1.4,
                'lv2_ap_cost' => 6,
                'lv3_percent' => 2.0,
                'lv3_ap_cost' => 10,
                'elemental_id' => 1,
                'description' => SkillDefinition::MagicMissile->description(),
            ],
            [
                'id' => SkillDefinition::GuardSpell->value,
                'name' => SkillDefinition::GuardSpell->label(),
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'is_target_enemy' => false,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 5,
                'lv1_buff_turn' => 4,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 8,
                'lv2_buff_turn' => 5,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 10,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => SkillDefinition::GuardSpell->description(),
            ],
            [
                'id' => SkillDefinition::AttackSpell->value,
                'name' => SkillDefinition::AttackSpell->label(),
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'is_target_enemy' => false,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 5,
                'lv1_buff_turn' => 4,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 8,
                'lv2_buff_turn' => 5,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 10,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => SkillDefinition::AttackSpell->description(),
            ],
            [
                'id' => SkillDefinition::MagicSpell->value,
                'name' => SkillDefinition::MagicSpell->label(),
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'is_target_enemy' => false,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 5,
                'lv1_buff_turn' => 4,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 8,
                'lv2_buff_turn' => 5,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 10,
                'lv3_buff_turn' => 6,
                'elemental_id' => 1,
                'description' => SkillDefinition::MagicSpell->description(),
            ],
            /*
            [
                'id' => '64',
                'name' => 'スキル64',
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '65',
                'name' => 'スキル65',
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '66',
                'name' => 'スキル66',
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '67',
                'name' => 'スキル67',
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '68',
                'name' => 'スキル68',
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            [
                'id' => '69',
                'name' => 'スキル69',
                'available_role_id' => Role::ROLE_BUFFER,
                'attack_type' => AttackType::NoType->value,
                'effect_type' => EffectType::Buff->value,
                'target_range' => TargetRange::Single->value,
                'lv1_percent' => 0.5,
                'lv1_ap_cost' => 2,
                'lv1_buff_turn' => 3,
                'lv2_percent' => 0.7,
                'lv2_ap_cost' => 2,
                'lv2_buff_turn' => 3,
                'lv3_percent' => 1.0,
                'lv3_ap_cost' => 2,
                'lv3_buff_turn' => 3,
                'elemental_id' => 1,
                'description' => '味方単体の守備力をアップさせる。',
            ],
            */

            // 敵の使用するスキル 100番以降

        ];

        foreach ($seeds as $seed) {
            Skill::create($seed);
        }

    }
}
